# Generated by Django 3.1.5 on 2021-01-16 23:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.UploadToPathAndRename('images/'))),
            ],
            options={
                'verbose_name_plural': 'queries',
            },
        ),
    ]
